### ISSUE TITLE
Where can I get sources for version 1.4?

### ISSUE THREAD

**Issue by bvn13** [smooks/unedifact#11]
Where?

**Comment by manish-in-java** [comment]
@bvn13, version 1.4 is tagged in the repository. If you have the repository cloned somewhere, switching to the tag as `git checkout v1.4` will suffice. If you do not have the repository, you can download the code as a ZIP file from the [page dedicated to release 1.4](https://github.com/smooks/unedifact/releases/tag/v1.4).
