### ISSUE TITLE
Cannot extract d93a zip file

### ISSUE THREAD

**Issue by ahmetbombaci-united** [smooks/unedifact#30]
I cannot extract zip file (d93a.zip). What might be the reason?

**Comment by manish-in-java** [comment]
@ahmetbombaci-united, which ZIP file are you referring to? How are you attempting to extract it? Have you tried different archive managers, like 7-ZIP, etc.?

**Comment by ahmetbombaci** [comment]
@manish-in-java I used 7-zip yesterday in a Windows PC. Today, I tried from my personal laptop where Ubuntu is installed and still getting the same error: 

There was an error while extracting "d93a.zip".
'd93a.zip': not an archive

Please note that I would like to review the implementation of the parser. I just tried another one: d01b.zip but I got the same error.

**Comment by manish-in-java** [comment]
@ahmetbombaci-united, I am able to open all files just fine. In fact, the build process requires the ZIP files to be valid to be able to generate the mappings. Can you post the steps to reproduce the problem - what command, which application, etc.?

I am also unclear about your comment on reviewing the parser implementation. The ZIP files in this repository are the EDIFACT message directories. They contain only RFC-style text files. There is no Java code in this repository. The Java code that parses the text files [is in a different repository](https://github.com/smooks/smooks/tree/master/edi) as two different Maven plugins. The ECT plugin parses the text files and generates XML binding files from them. Then, the EJC plugin generates Java code from the binding files.
