### ISSUE TITLE
Can't build module with maven

### ISSUE THREAD

**Issue by artaxerxe** [smooks/unedifact#9]
Hello,

I tried to build master and tag v1.6.0 with Java 1.8, maven 3.3.9.
I cd into main directory, and try "mvn clean install" command.
I get the following output: 

    [ERROR] Failed to execute goal org.milyn:maven-ect-plugin:1.6:generate (default) on project d93a-mapping: Execution default of goal org.milyn:maven-ect-plugin:1.6:generate failed: A required class was missing while executing org.milyn:maven-ect-plugin:1.6:generate: org/eclipse/emf/ecore/EStructuralFeature
    [ERROR] -----------------------------------------------------
    [ERROR] realm =    plugin>org.milyn:maven-ect-plugin:1.6
    [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
    [ERROR] urls[0] = file:/home/artaxerxe/.m2/repository/org/milyn/maven-ect-plugin/1.6/maven-ect-plugin-1.6.jar
    [ERROR] urls[1] = file:/home/artaxerxe/.m2/repository/org/codehaus/plexus/plexus-utils/1.0.4/plexus-utils-1.0.4.jar
    [ERROR] urls[2] = file:/home/artaxerxe/.m2/repository/org/jfrog/maven/annomojo/maven-plugin-anno/1.3.1/maven-plugin-anno-1.3.1.jar
    [ERROR] urls[3] = file:/home/artaxerxe/.m2/repository/org/milyn/milyn-smooks-ect/1.6/milyn-smooks-ect-1.6.jar
    [ERROR] urls[4] = file:/home/artaxerxe/.m2/repository/org/milyn/milyn-smooks-edi/1.6/milyn-smooks-edi-1.6.jar
    [ERROR] urls[5] = file:/home/artaxerxe/.m2/repository/org/milyn/milyn-edisax-parser/1.6/milyn-edisax-parser-1.6.jar
    [ERROR] urls[6] = file:/home/artaxerxe/.m2/repository/org/milyn/milyn-commons/1.6/milyn-commons-1.6.jar
    [ERROR] urls[7] = file:/home/artaxerxe/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
    [ERROR] urls[8] = file:/home/artaxerxe/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
    [ERROR] urls[9] = file:/home/artaxerxe/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar
    [ERROR] urls[10] = file:/home/artaxerxe/.m2/repository/javassist/javassist/3.10.0.GA/javassist-3.10.0.GA.jar
    [ERROR] urls[11] = file:/home/artaxerxe/.m2/repository/org/milyn/milyn-smooks-javabean/1.6/milyn-smooks-javabean-1.6.jar
    [ERROR] urls[12] = file:/home/artaxerxe/.m2/repository/org/milyn/milyn-smooks-core/1.6/milyn-smooks-core-1.6.jar
    [ERROR] urls[13] = file:/home/artaxerxe/.m2/repository/com/thoughtworks/xstream/xstream/1.4.1/xstream-1.4.1.jar
    [ERROR] urls[14] = file:/home/artaxerxe/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar
    [ERROR] urls[15] = file:/home/artaxerxe/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
    [ERROR] urls[16] = file:/home/artaxerxe/.m2/repository/org/mvel/mvel2/2.0.17/mvel2-2.0.17.jar
    [ERROR] urls[17] = file:/home/artaxerxe/.m2/repository/jaxen/jaxen/1.1.1/jaxen-1.1.1.jar
    [ERROR] urls[18] = file:/home/artaxerxe/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar
    [ERROR] urls[19] = file:/home/artaxerxe/.m2/repository/jdom/jdom/1.0/jdom-1.0.jar
    [ERROR] urls[20] = file:/home/artaxerxe/.m2/repository/xml-apis/xml-apis/1.3.02/xml-apis-1.3.02.jar
    [ERROR] urls[21] = file:/home/artaxerxe/.m2/repository/xom/xom/1.0/xom-1.0.jar
    [ERROR] urls[22] = file:/home/artaxerxe/.m2/repository/dtdparser/dtdparser/1.21/dtdparser-1.21.jar
    [ERROR] urls[23] = file:/home/artaxerxe/.m2/repository/javax/transaction/jta/1.1/jta-1.1.jar
    [ERROR] urls[24] = file:/home/artaxerxe/.m2/repository/org/apache/ant/ant/1.7.0/ant-1.7.0.jar
    [ERROR] urls[25] = file:/home/artaxerxe/.m2/repository/org/apache/ant/ant-launcher/1.7.0/ant-launcher-1.7.0.jar
    [ERROR] urls[26] = file:/home/artaxerxe/.m2/repository/org/eclipse/xsd/org.eclipse.xsd/2.7.0-v20110606-0949/org.eclipse.xsd-2.7.0-v20110606-0949.jar
    [ERROR] urls[27] = file:/home/artaxerxe/.m2/repository/org/eclipse/emf/org.eclipse.emf.ecore/2.7.0-v20110605-0747/org.eclipse.emf.ecore-2.7.0-v20110605-0747.jar
    [ERROR] urls[28] = file:/home/artaxerxe/.m2/repository/org/eclipse/emf/org.eclipse.emf.common/2.6.0.v20100614-1136/org.eclipse.emf.common-2.6.0.v20100614-1136.jar
    [ERROR] Number of foreign imports: 1
    [ERROR] import: Entry[import  from realm ClassRealm[project>org.milyn.edi:unedifact-gen-parent:1.6, parent: ClassRealm[maven.api, parent: null]]]
    [ERROR] 
    [ERROR] -----------------------------------------------------: org.eclipse.emf.ecore.EStructuralFeature
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :d93a-mapping

Can anybody help me on how to build this?

Thanks in advance,
Andrei M.

**Comment by manish-in-java** [comment]
@artaxerxe, can you try building the master branch with JDK 1.6 and Maven 3.2? New versions have been published to Maven Central, so the build is working fine now.

**Comment by manish-in-java** [comment]
Closing as there has been no response from the originator and the builds are working fine.
